version: '3'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    
  s3-to-dynamodb:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dynamodb-local
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - S3_BUCKET=spotify-streaming-data
      - S3_KEY=${LATEST_S3_KEY:-kpi_genre_duration/}
      - PROCESS_SINGLE_FILE=true
      - DYNAMODB_TABLE=spotify_genre_duration
      - USE_LOCAL_DYNAMODB=true
      - USE_REAL_S3=true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
