FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

# Copy scripts
COPY processing-script.py /app/

# Run the script
CMD ["python", "processing-script.py"]
