version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    networks:
      - wiki_scraper_network
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - wiki_scraper_network
    ports:
      - "27017:27017"  # MongoDB default port
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - wiki_scraper_network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    # volumes:
      # - redis_data:/data

  parser:
    image: mickaelbalensi/parser:latest
    build: ./parser
    container_name: parser-container
    networks:
      - wiki_scraper_network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      rabbitmq:
        condition: service_healthy
      

  fetcher:
    image: mickaelbalensi/fetcher:latest
    build: ./fetcher
    container_name: fetcher-container
    networks:
      - wiki_scraper_network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - ./html_pages:/app/html_pages

  filter:
    image: mickaelbalensi/filter:latest
    build:
      context: ./filter
    container_name: filter-container
    networks:
      - wiki_scraper_network
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - REDIS_HOST=redis
      - REDIS_PORT=6379

networks:
  wiki_scraper_network:
    driver: bridge

volumes:
  mongo_data:
  redis_data: