version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    networks:
      - wiki_scraper_network
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - wiki_scraper_network
    ports:
      - "27017:27017"  # MongoDB default port
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mongo_data:/data/db

  parser:
    image: mickaelbalensi/parser:latest
    build: ./parser
    container_name: parser-container
    networks:
      - wiki_scraper_network
    environment:
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
      

  fetcher:
    image: mickaelbalensi/fetcher:latest
    build: ./fetcher
    container_name: fetcher-container
    networks:
      - wiki_scraper_network
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongo:
        condition: service_healthy
    volumes:
      - ./html_pages:/app/html_pages

  

networks:
  wiki_scraper_network:
    driver: bridge

volumes:
  mongo_data: