version: '3.8'

services:
  glue-etl:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    volumes:
      - .:/glue-scripts
    command: ["spark-submit", "--master", "local[*]", "/glue-scripts/spotify_etl.py"]
