# Use official Python base image
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy only the requirements first (this prevents unnecessary reinstallation)
COPY requirements.txt /app/

RUN pip install --no-cache-dir -r /app/requirements.txt

# Copy the current directory contents into the container at /app
COPY . /app

# Install necessary Python dependencies

# Expose the port if needed for your app
EXPOSE 5000

# Command to run the categorizer script
CMD ["python", "categorizer.py"]
